#!/bin/bash

# Corporate Services Filter & Search - Quick Test Guide
# This script provides commands to test all functionality

echo "🔍 Corporate Services Filter & Search Test Guide"
echo "=================================================="
echo ""

echo "Step 1: Start Backend Server"
echo "Command: cd cashper_backend && python run_server.py"
echo "Expected: Server running on http://127.0.0.1:8000"
echo ""

echo "Step 2: Start Frontend Server"  
echo "Command: cd cashper_frontend && npm run dev"
echo "Expected: Frontend running on http://localhost:4208 (or similar)"
echo ""

echo "Step 3: Open Browser and Navigate"
echo "URL: http://localhost:4208"
echo "Find: Dashboard > Corporate Services"
echo ""

echo "TEST CASES"
echo "=========="
echo ""

echo "✅ TEST 1: Basic Search"
echo "1. Type 'Sudha' in search box"
echo "2. Expected: Shows 2 applications (Sudha Yadav's registrations)"
echo "3. Try: 'john', '8382998889', 'Tech Solutions', etc."
echo ""

echo "✅ TEST 2: Status Filter"
echo "1. Click 'All Status' dropdown"
echo "2. Select 'Pending'"
echo "3. Expected: Shows only pending applications"
echo "4. Pagination resets to page 1"
echo "5. Try: Under Review, Approved, In Progress, Completed"
echo ""

echo "✅ TEST 3: Service Filter"
echo "1. Click 'All Services' dropdown"
echo "2. Select 'Register New Company'"
echo "3. Expected: Shows only registration applications"
echo "4. Try: 'Compliance for New Company', 'Tax Audit'"
echo ""

echo "✅ TEST 4: Combined Filters"
echo "1. Status = 'Pending'"
echo "2. Service = 'Register New Company'"
echo "3. Search = 'Sudha'"
echo "4. Expected: ONLY pending registrations by Sudha Yadav"
echo "5. Change any filter → Results update immediately"
echo ""

echo "✅ TEST 5: View Application Details"
echo "1. Search or filter to show applications"
echo "2. Click 'View' button on any application"
echo "3. Modal opens showing:"
echo "   - Application ID (monospace)"
echo "   - Company Name"
echo "   - Service Type"
echo "   - Email"
echo "   - Contact"
echo "   - Applied Date"
echo "   - Status (with color)"
echo "4. Close modal with X button"
echo ""

echo "✅ TEST 6: Pagination"
echo "1. With filters showing >5 results"
echo "2. See pagination controls at bottom"
echo "3. Click 'Next' to go to page 2"
echo "4. Click 'Previous' to go back"
echo "5. Click page number to jump to that page"
echo ""

echo "✅ TEST 7: Export CSV"
echo "1. Apply filters (or use 'All')"
echo "2. Find export button"
echo "3. Click to download CSV"
echo "4. File should contain filtered results"
echo ""

echo "✅ TEST 8: Real-time Updates"
echo "1. Keep page open for 10 seconds"
echo "2. New applications should auto-load"
echo "3. No interruption if form popup is open"
echo ""

echo "KNOWN DATA IN DATABASE"
echo "====================="
echo ""
echo "Company Registrations (Register New Company):"
echo "- Sudha Yadav - kumuyadav249@gmail.com - 8382998889"
echo "- John Doe - john@example.com - 9876543210"
echo "- Rajesh Kumar Singh - rajesh.kumar@example.com - 9876543210"
echo "- Multiple test users"
echo ""

echo "All Status Types: Pending, Under Review, Approved, In Progress, Completed"
echo ""

echo "TROUBLESHOOTING"
echo "==============="
echo ""
echo "❌ No applications showing?"
echo "✓ Check backend is running (http://127.0.0.1:8000)"
echo "✓ Check browser console for errors (F12)"
echo "✓ Clear cache and refresh (Ctrl+Shift+R)"
echo "✓ Verify MongoDB is running"
echo ""

echo "❌ Search not working?"
echo "✓ Verify search includes: name, email, service, contact, ID"
echo "✓ Check that search is case-insensitive"
echo "✓ Make sure pagination resets (page 1) on search"
echo ""

echo "❌ Filters not showing results?"
echo "✓ Make sure service filter only has 3 options"
echo "✓ Check that you're not filtering for non-existent combinations"
echo "✓ Verify status values match: Pending, Under Review, Approved, In Progress, Completed"
echo ""

echo "✅ ALL TESTS COMPLETE!"
echo ""
